# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae96efc4c9296eb4b66e090d7a98f9ca8ebcb4bc8dc955ef77ffcb49b6a9a21499b9e8b74a34e2a03015d06fd0a11241992de61bc56e1b96a9faa8df18813ee1

test:
  secret_key_base: 709d9b83438e8ef5086fd0d7c3f248be21f387edb5e6de582387dc39775fae8f86c3f401f2ff44a3ac555cf02441c5755dbd1ee7d9c0ad8c24386f8cdaf91b3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
